deployment:
  tasks:
    - export DEPLOYPATH=/home/amirul1do/shop-management-laravel-api
    # Go to the repository directory
    - /bin/echo "🔄 Pulling latest changes..."
    - /bin/git -C $DEPLOYPATH pull origin main       # change branch if needed

    # Install composer deps
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader -d $DEPLOYPATH

    - /bin/echo "✅ Deployment finished!"
