---
deployment:
  tasks:
    # 1. Set deployment path (change to your public_html subfolder if Laravel is not directly in it)
    - export DEPLOYPATH=/home/amirul1do/shop-management-laravel-api

    # 2. Install Composer dependencies
    - /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --working-dir=$DEPLOYPATH

    # 3. Run database migrations
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan migrate --force

    # 4. Clear and rebuild caches
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan config:clear
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan cache:clear
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan route:clear
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan view:clear
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan config:cache
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan route:cache
    - /opt/cpanel/composer/bin/php $DEPLOYPATH/artisan view:cache

    # 5. Set correct permissions for Laravel writable directories
    - /bin/find $DEPLOYPATH/storage -type d -exec chmod 775 {} \;
    - /bin/find $DEPLOYPATH/bootstrap/cache -type d -exec chmod 775 {} \;
    - /bin/find $DEPLOYPATH/storage -type f -exec chmod 664 {} \;
    - /bin/find $DEPLOYPATH/bootstrap/cache -type f -exec chmod 664 {} \;
